name = "fireroad"
license = "GPLv2"
licenselink = "https://github.com/bdfinst/fireroad/blob/master/LICENSE.md"
description = "fireroad is a responsive, clean and content-focused Hugo theme."
homepage = "https://github.com/bdfinst/fireroad/"
demosite = "https://fireroad-demo.netlify.app/"
tags = ["blog", "responsive", "light", "multilingual", "customizable", "widgets", "wordpress"]
features = ["blog", "responsive", "multilingual", "widgets", "rss", "disqus", "google analytics", "wordpress"]
min_version = "0.48"

[author]
  name = "bdfinst"
  homepage = "https://github.com/bdfinst"

# If porting an existing theme
[original]
  name = "Mainroad"
  homepage = "https://mainroad-demo.netlify.app"
  repo = "https://github.com/Vimux/Mainroad"
